### ISSUE TITLE
No consigo que cargue los municipios

### ISSUE THREAD

**Issue by daguilarm** [IagoLast/pselect#1]
Hola, parece que hay algún problema porque no consigo que funcionen los municipios... no cargan, y no da ningún error de js.

**Comment by IagoLast** [comment]
Puedo ver el código?

**Comment by daguilarm** [comment]
He subido el ejemplo
http://boiling-fortress-4006.herokuapp.com/

**Comment by daguilarm** [comment]
el código que he probado es exactamente el del ejemplo que tienes.

**Comment by IagoLast** [comment]
No va el link...

**Comment by daguilarm** [comment]
si, es que ha funcionado solo un rato, voy a intentar subirlo otra vez

**Comment by daguilarm** [comment]
http://fierce-garden-7486.herokuapp.com/

**Comment by IagoLast** [comment]
Arreglado, mea culpa

**Comment by daguilarm** [comment]
gracias
