### ISSUE TITLE
campos seleccionados por defecto

### ISSUE THREAD

**Issue by binibin** [IagoLast/pselect#2]
Hola, 
¿Cómo puedo seleccionar por defecto una determinada provincia ($provincia) y localidad ($localdiad)?
Muchas gracias!

**Comment by IagoLast** [comment]
@binibin  tienes que utilizar jQuery para que lance eventos una vez la página se ha cargado.

Este seria un ejemplo completo para selecionar un municipio de Albacete, la clave esta en el script del final.
```html
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
	<title>Ejemplo Select provincias Españolas.</title>
</head>

<body>
	<h2>Seleccione provincia.</h2>
	<select class="ps-prov"></select>
	<select class="ps-mun"></select>
	<script type="text/javascript" src="bower_components/jquery/dist/jquery.min.js"></script>
	<script type="text/javascript" src="dist/pselect.min.js"></script>
	<script type="text/javascript">
	$().ready(function() {
		$(".ps-prov").val("02");
		$(".ps-prov").change();
		$(".ps-mun").val("51");
	});
	</script>
</body>

</html>
```

Esto funciona con la version 0.1.0 te recomiendo que te bajes el codigo de nuevo o utilices bower.
