### ISSUE TITLE
Nombre de provincia como value

### ISSUE THREAD

**Issue by caralgar** [IagoLast/pselect#3]
Hola, ¿cómo podría asignar el valor del nombre tanto en municipio como en provincia en lugar del código? De forma que al enviar el formulario sea el dato que se envíe.

He añadido un data-attribute con el código de provincia y le he asignado al value el nombre, sin embargo a la hora de filtrar los municipios no consigo leer el atributo data para poder obtener el listado asociado a la provincia.

Así asigno el atributo data-code y el nombre al value:
`$(provinceCssSelector).append($('<option>').text(province.name).attr('value', province.name).attr('data-code', province.code));`

Esta línea debería cambiarla para buscar el valor de la provincia el data-code:
`var selectedProvince = this.value;`

He probado `var selectedProvince = $(this).data('code');` y otras opciones, pero ninguna me funciona. ¿Alguna idea?

¡Gracias!

**Comment by IagoLast** [comment]
@caralgar no entiendo muy bien la cuestión...

Si lo que quieres es el "nombre" de la provincia/municipio prueba a utilizar directamente el texto del select en lugar del atributo.

**Comment by caralgar** [comment]
El problema que tenía es que al enviar el formulario los datos que se enviaban era el código de provincia y municipio en lugar del nombre. Al final lo acabé solucionando de una manera muy sencilla.

Gracias. Un saludo!
